sudo: required

services:
  - docker

before_install:
  - docker build -t camboim/zaivu .

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push camboim/zaivu

deploy:
  provider: elasticbeanstaslk
  region: sa-east-1
  app: Zaivu
  env: ZaivuEnv
  bucket-name: elasticbeanstalk-sa-east-1-602085452522
  bucket_path: Zaivu
  on:
    branch: master
  acess_key_id: $AWS_ACESS_KEY
  secret_acess_key: $AWS_SECRET_KEY
